const $=id=>document.getElementById(id);
const state={scene:'product_governance',conversation:null,conversations:[],messages:[],assets:[],pending:[],events:[],progress:[],actions:[],providers:[],ws:null,reconnectTimer:null,busy:false};
const SCENES={product_governance:{name:'商品治理',meta:'核对商品信息、素材、资质与风险声明。'},merchant_review:{name:'商家审核',meta:'核对主体、资质、授权与历史风险。'},aftersales:{name:'售后判责',meta:'结合订单、履约、沟通记录和举证还原事实。'},risk_review:{name:'风险核查',meta:'交叉确认交易、账户、商品与履约异常。'},content_audit:{name:'内容审核',meta:'检查图片、视频、文案与商品事实的一致性。'}};
const ICON={image:'图',video:'视',audio:'音',text:'文',document:'档',sheet:'表',file:'件',tool_result:'核'};
function esc(s=''){return String(s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function fmtTime(ts){try{return new Date(ts*1000).toLocaleString('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'})}catch{return''}}
function fmtSize(n=0){if(n<1024)return `${n} B`;if(n<1024**2)return `${(n/1024).toFixed(1)} KB`;return `${(n/1024**2).toFixed(1)} MB`}
function kindOf(a){return a?.meta?.kind||((a?.mime||'').startsWith('image/')?'image':(a?.mime||'').startsWith('video/')?'video':(a?.mime||'').startsWith('audio/')?'audio':'file')}
function kindLabel(a){const k=kindOf(a),m=a.meta||{};if(k==='image')return `图片${m.width?` · ${m.width}×${m.height}`:''}`;if(k==='video')return `视频${m.duration?` · ${m.duration}s`:''}`;if(k==='audio')return `音频${m.duration?` · ${m.duration}s`:''}`;if(k==='document')return `文档${m.pages?` · ${m.pages}页`:''}`;if(k==='sheet')return `表格${m.rows?` · ${m.rows}行`:''}`;if(k==='text')return `文本${m.lines?` · ${m.lines}行`:''}`;return fmtSize(a.size||0)}
async function api(url,opts={}){const o={...opts};if(o.body && typeof o.body==='string')o.headers={'content-type':'application/json',...(o.headers||{})};const r=await fetch(url,o);if(!r.ok){let msg=`请求失败 ${r.status}`;try{const d=await r.json();msg=d.detail||msg}catch{}throw new Error(msg)}return r.status===204?null:r.json()}
let toastTimer;function toast(msg){const el=$('toast');el.textContent=msg;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),2200)}
function md(s=''){let x=esc(s);x=x.replace(/^###\s+(.+)$/gm,'<h3>$1</h3>').replace(/\*\*(.+?)\*\*/g,'<strong>$1</strong>').replace(/^\d+\.\s+(.+)$/gm,'<div class="md-line">$1</div>').replace(/\n/g,'<br>');return x}
function setScene(scene){state.scene=scene;document.querySelectorAll('.scene').forEach(x=>x.classList.toggle('active',x.dataset.scene===scene));const s=SCENES[scene]||SCENES.product_governance;$('sceneEyebrow').textContent=s.name;if(!state.conversation){$('conversationTitle').textContent='新的业务任务';$('conversationMeta').textContent=s.meta}}
async function loadProviders(){state.providers=await api('/api/providers');$('providerSelect').innerHTML=state.providers.map(p=>`<option value="${esc(p.key)}">${esc(p.name)}${p.key!=='auto'&&p.key!=='demo'&&!p.configured?' · 未配置':''}</option>`).join('');$('providerGrid').innerHTML=state.providers.filter(p=>p.key!=='auto').map(p=>`<div class="provider-card"><div class="provider-logo">${esc((p.name||'服').slice(0,2))}</div><div><b>${esc(p.name)}</b><p>${esc(p.note||p.vendor||'')}</p></div><span class="provider-status ${p.configured?'ok':''}">${p.configured?'可用':'未配置'}</span></div>`).join('')}
async function loadConversations(){state.conversations=await api('/api/conversations');renderConversationList()}
function setConversationUrl(id){const u=new URL(location.href);if(id)u.searchParams.set('conversation',id);else u.searchParams.delete('conversation');history.replaceState(null,'',u)}
function disconnectConversation(){clearTimeout(state.reconnectTimer);state.reconnectTimer=null;if(state.ws){const ws=state.ws;state.ws=null;try{ws.close()}catch{}}}
function deriveBusy(events=[]){const accepted=[...events].reverse().find(e=>e.type==='message.accepted');if(!accepted)return false;const terminal=[...events].reverse().find(e=>e.type==='answer.ready'||e.type==='answer.error');return !terminal||terminal.id<accepted.id}
function latestProgress(events=[]){const accepted=[...events].reverse().find(e=>e.type==='message.accepted');const cutoff=accepted?.id||0;return events.filter(e=>e.type==='progress'&&e.id>cutoff).map(e=>e.payload)}
function renderConversationList(){const box=$('conversationList');box.innerHTML=state.conversations.length?state.conversations.map(c=>`<button class="conv-item ${state.conversation?.id===c.id?'active':''}" data-id="${c.id}"><b>${esc(c.title)}</b><small>${esc(SCENES[c.scene]?.name||'业务任务')} · ${fmtTime(c.updated_at)}</small></button>`).join(''):'<div class="progress-empty">还没有历史任务</div>';box.querySelectorAll('.conv-item').forEach(b=>b.onclick=()=>openConversation(b.dataset.id))}
async function newConversation(scene=state.scene){disconnectConversation();setScene(scene);const c=await api('/api/conversations',{method:'POST',body:JSON.stringify({title:'新的业务任务',scene})});state.conversation=c;state.messages=[];state.assets=[];state.pending=[];state.events=[];state.progress=[];state.actions=[];state.busy=false;$('sendBtn').disabled=false;setConversationUrl(c.id);renderAll();connectConversation();await loadConversations();$('messageInput').focus()}
async function openConversation(id){disconnectConversation();const d=await api(`/api/conversations/${id}`);state.conversation=d;state.scene=d.scene;state.messages=d.messages||[];state.assets=d.assets||[];state.events=d.events||[];state.actions=d.actions||[];state.pending=[];state.progress=latestProgress(state.events);state.busy=deriveBusy(state.events);$('sendBtn').disabled=state.busy;setConversationUrl(d.id);setScene(d.scene);renderAll();connectConversation();renderConversationList();scrollBottom(false)}
function renderAll(){const c=state.conversation;$('conversationTitle').textContent=c?.title||'新的业务任务';$('conversationMeta').textContent=SCENES[state.scene]?.meta||'';$('welcomePanel').hidden=state.messages.length>0;renderMessages();renderAssets();renderPending();renderProgress();renderActions();const latest=[...state.messages].reverse().find(m=>m.role==='assistant');renderEvidence(latest?.payload?.evidence||[]);renderSuggestions(latest?.payload?.suggestions||[])}
function renderMessages(){const box=$('messageList');box.innerHTML=state.messages.map(m=>renderMessage(m)).join('')}
function renderMessage(m){const p=m.payload||{};const aids=p.asset_ids||[];const msgAssets=aids.map(id=>state.assets.find(a=>a.id===id)).filter(Boolean);if(m.role==='user')return `<div class="msg user"><div class="msg-body"><div class="msg-content">${esc(m.content)}</div>${renderMsgAssets(msgAssets)}</div></div>`;return `<div class="msg assistant"><div class="msg-body"><div class="msg-label"><span class="assistant-logo">EE</span><b>EcomEvo</b><span>${m.created_at?fmtTime(m.created_at):''}</span></div><div class="msg-content">${md(m.content)}</div><div class="answer-foot"><span class="answer-provider">由 ${esc(p.provider||'工作台')} 完成</span><button class="answer-action" data-copy="${esc(m.id)}">复制</button></div></div></div>`}
function renderMsgAssets(rows){if(!rows.length)return'';return `<div class="msg-assets">${rows.map(a=>{const k=kindOf(a),visual=k==='image'?`<img class="msg-thumb" src="/api/assets/${a.id}/file">`:k==='video'?`<img class="msg-thumb" src="/api/assets/${a.id}/preview/0">`:`<i>${ICON[k]||'件'}</i>`;return `<div class="msg-asset">${visual}<div><b>${esc(a.name)}</b><small>${esc(kindLabel(a))}</small></div></div>`}).join('')}</div>`}
function renderPending(){const box=$('pendingAssets');box.hidden=!state.pending.length;box.innerHTML=state.pending.map((a,i)=>{const k=kindOf(a);const thumb=k==='image'?`<img class="thumb" src="/api/assets/${a.id}/file">`:`<span class="thumb">${ICON[k]||'件'}</span>`;return `<div class="pending-asset">${thumb}<div><b>${esc(a.name)}</b><small>${esc(kindLabel(a))}</small></div><button data-rm="${i}">×</button></div>`}).join('');box.querySelectorAll('[data-rm]').forEach(b=>b.onclick=()=>{state.pending.splice(Number(b.dataset.rm),1);renderPending()})}
function renderAssets(){const box=$('assetList');box.innerHTML=state.assets.length?state.assets.map(a=>`<div class="asset-card"><div class="asset-icon">${ICON[kindOf(a)]||'件'}</div><div><b>${esc(a.name)}</b><small>${esc(kindLabel(a))}<br>${fmtSize(a.size||0)}</small></div></div>`).join(''):'<div class="empty-side">还没有添加资料。</div>'}
function renderEvidence(rows=[]){const box=$('evidenceList');box.innerHTML=rows.length?rows.map(e=>{const a=e.asset_id?state.assets.find(x=>x.id===e.asset_id):null;let media='';if(a&&kindOf(a)==='image')media=`<div class="evidence-media"><img src="/api/assets/${a.id}/file"></div>`;else if(a&&kindOf(a)==='video')media=`<div class="evidence-media"><img src="/api/assets/${a.id}/preview/0"><span>视频关键帧</span></div>`;return `<div class="evidence-card">${media}<div class="evidence-top"><div class="evidence-icon">${ICON[e.kind]||ICON[kindOf(a)]||'核'}</div><div><em>${e.source==='upload'?'业务资料':'核对结果'}</em><b>${esc(e.title)}</b><small>${esc(e.detail||'已关联到当前结论')}</small></div></div></div>`}).join(''):'<div class="empty-side">完成一次处理后显示。</div>'}
function renderProgress(){const rows=state.progress;const last=rows.at(-1);const pct=last?.percent||0;$('statusPercent').textContent=pct;$('statusBar').style.width=`${pct}%`;document.querySelector('.status-ring').style.setProperty('--p',`${pct}%`);$('taskState').textContent=last?.step||'等待任务';$('taskDetail').textContent=last?.detail||'发一句问题，或者先添加资料。';$('progressList').innerHTML=rows.length?rows.map((p,i)=>`<div class="progress-item ${i<rows.length-1||p.percent>=100?'done':''}"><span>${i<rows.length-1||p.percent>=100?'✓':i+1}</span><div><b>${esc(p.step)}</b><small>${esc(p.detail||'')}</small></div></div>`).join(''):'<div class="progress-empty">任务开始后，这里会同步显示处理进度。</div>'}
function renderSuggestions(rows=[]){const r=rows.length?rows:['继续补充资料','只看高风险项','把结论整理成清单'];$('suggestionList').innerHTML=r.map(x=>`<button>${esc(x)}</button>`).join('');$('suggestionList').querySelectorAll('button').forEach(b=>b.onclick=()=>{$('messageInput').value=b.textContent;autoSize();$('messageInput').focus()})}
function renderActions(){const box=$('actionList');box.innerHTML=state.actions.length?state.actions.map(a=>`<div class="action-card"><span class="action-status ${a.status}">${statusText(a.status)}</span><h4>${esc(a.title)}</h4><p>${esc(a.description)}</p><div class="action-meta"><span class="risk-chip ${a.risk_level}">${riskText(a.risk_level)}</span><span class="risk-chip">${a.side_effect?'会改变业务状态':'仅保存记录'}</span></div>${a.status==='proposed'&&a.requires_confirmation?`<div class="action-buttons"><button class="reject" data-action="${a.id}" data-decision="reject">暂不执行</button><button class="approve" data-action="${a.id}" data-decision="approve">确认执行</button></div>`:''}</div>`).join(''):'<div class="empty-side">目前没有待确认操作。</div>';box.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>decideAction(b.dataset.action,b.dataset.decision))}
function statusText(s){return({proposed:'等待确认',approved:'已确认',executed:'已执行',rejected:'已取消',failed:'执行失败'})[s]||s}function riskText(s){return({low:'低影响',medium:'中等影响',high:'高影响'})[s]||s}
async function decideAction(id,decision){try{const row=await api(`/api/actions/${id}/decision`,{method:'POST',body:JSON.stringify({decision,note:''})});const i=state.actions.findIndex(x=>x.id===id);if(i>=0)state.actions[i]=row;renderActions();toast(decision==='approve'?'操作已执行并留痕':'已取消本次操作')}catch(err){toast(err.message)}}
function connectConversation(){
  if(!state.conversation)return;
  const cid=state.conversation.id,proto=location.protocol==='https:'?'wss':'ws';
  const ws=new WebSocket(`${proto}://${location.host}/ws/conversations/${cid}`);state.ws=ws;
  ws.onmessage=e=>handleEvent(JSON.parse(e.data));ws.onerror=()=>{};
  ws.onclose=()=>{if(state.ws===ws)state.ws=null;if(state.conversation?.id!==cid)return;clearTimeout(state.reconnectTimer);state.reconnectTimer=setTimeout(async()=>{if(state.conversation?.id!==cid)return;try{const d=await api(`/api/conversations/${cid}`);if(state.conversation?.id!==cid)return;state.messages=d.messages||[];state.assets=d.assets||[];state.events=d.events||[];state.actions=d.actions||[];state.progress=latestProgress(state.events);state.busy=deriveBusy(state.events);$('sendBtn').disabled=state.busy;renderAll();connectConversation()}catch{}},1200)};
}
function handleEvent(ev){if(ev.type==='heartbeat')return;if(ev.id&&state.events.some(x=>x.id===ev.id))return;state.events.push(ev);if(ev.type==='progress'){state.progress.push(ev.payload);renderProgress();$('workCard').hidden=false;$('workStep').textContent=ev.payload.step;$('workDetail').textContent=ev.payload.detail;$('workPercent').textContent=`${ev.payload.percent||0}%`;$('workBar').style.width=`${ev.payload.percent||0}%`;scrollBottom()}if(ev.type==='answer.ready'){state.busy=false;$('sendBtn').disabled=false;$('workCard').hidden=true;if(!state.messages.some(m=>m.id===ev.payload.message?.id))state.messages.push(ev.payload.message);state.actions=ev.payload.actions||state.actions;renderMessages();renderEvidence(ev.payload.result?.evidence||[]);renderSuggestions(ev.payload.result?.suggestions||[]);renderActions();loadConversations();scrollBottom();if(state.actions.some(a=>a.status==='proposed'))setRightPanel('actions')}if(ev.type==='action.updated'){const row=ev.payload;const i=state.actions.findIndex(x=>x.id===row.id);if(i>=0)state.actions[i]=row;else state.actions.unshift(row);renderActions()}if(ev.type==='answer.error'){state.busy=false;$('sendBtn').disabled=false;$('workCard').hidden=true;toast(ev.payload.message||'处理失败')}}
async function uploadFiles(files){if(!files?.length)return;if(!state.conversation)await newConversation(state.scene);for(const file of files){const fd=new FormData();fd.append('file',file);fd.append('conversation_id',state.conversation.id);toast(`正在添加 ${file.name}`);try{const a=await api('/api/assets',{method:'POST',body:fd});state.pending.push(a);if(!state.assets.some(x=>x.id===a.id))state.assets.push(a);renderPending();renderAssets()}catch(err){toast(`添加失败：${err.message}`)}}}
async function sendMessage(){
  const input=$('messageInput'),text=input.value.trim();if(!text||state.busy)return;if(!state.conversation)await newConversation(state.scene);
  state.busy=true;$('sendBtn').disabled=true;const assetIds=state.pending.map(a=>a.id),pendingBefore=[...state.pending],localId='local-'+Date.now();
  state.messages.push({id:localId,role:'user',content:text,payload:{asset_ids:assetIds},created_at:Date.now()/1000});input.value='';autoSize();state.pending=[];renderPending();$('welcomePanel').hidden=true;renderMessages();state.progress=[];renderProgress();$('workCard').hidden=false;$('workStep').textContent='接收任务';$('workDetail').textContent='正在整理问题与业务资料';$('workPercent').textContent='5%';$('workBar').style.width='5%';scrollBottom();
  try{
    const accepted=await api(`/api/conversations/${state.conversation.id}/messages`,{method:'POST',body:JSON.stringify({content:text,asset_ids:assetIds,provider:$('providerSelect').value})});
    const i=state.messages.findIndex(m=>m.id===localId);if(i>=0&&accepted?.message)state.messages[i]=accepted.message;
    if(state.conversation?.title==='新的业务任务'){state.conversation.title=text.replace(/\n/g,' ').slice(0,30)||'新的业务任务';$('conversationTitle').textContent=state.conversation.title}
    renderMessages();loadConversations();
  }catch(err){
    state.busy=false;$('sendBtn').disabled=false;$('workCard').hidden=true;state.messages=state.messages.filter(m=>m.id!==localId);state.pending=pendingBefore;input.value=text;autoSize();renderMessages();renderPending();toast(err.message)
  }
}
function setRightPanel(name){document.querySelectorAll('.right-tab').forEach(x=>x.classList.toggle('active',x.dataset.panel===name));document.querySelectorAll('.right-panel').forEach(x=>x.classList.toggle('active',x.id===`panel-${name}`))}
function autoSize(){const t=$('messageInput');t.style.height='auto';t.style.height=Math.min(130,t.scrollHeight)+'px'}
function scrollBottom(smooth=true){requestAnimationFrame(()=>$('chatScroll').scrollTo({top:$('chatScroll').scrollHeight,behavior:smooth?'smooth':'auto'}))}
function bind(){document.querySelectorAll('.scene').forEach(x=>x.onclick=()=>newConversation(x.dataset.scene));document.querySelectorAll('.quick-card').forEach(x=>x.onclick=async()=>{try{const scene=x.dataset.scene;if(!state.conversation){await newConversation(scene)}else if(state.messages.length===0&&state.conversation.scene!==scene){state.conversation=await api(`/api/conversations/${state.conversation.id}`,{method:'PATCH',body:JSON.stringify({scene})});state.scene=scene;setScene(scene);await loadConversations()}else if(state.messages.length>0&&state.conversation.scene!==scene){await newConversation(scene)}else setScene(scene);$('messageInput').value=x.dataset.prompt;autoSize();$('messageInput').focus()}catch(err){toast(err.message)}});document.querySelectorAll('.right-tab').forEach(x=>x.onclick=()=>setRightPanel(x.dataset.panel));$('newTaskBtn').onclick=()=>newConversation(state.scene);$('refreshBtn').onclick=loadConversations;$('sendBtn').onclick=sendMessage;$('messageInput').oninput=autoSize;$('messageInput').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();sendMessage()}};document.querySelectorAll('.attach').forEach(b=>b.onclick=()=>{$('fileInput').accept=b.dataset.accept;$('fileInput').click()});$('fileInput').onchange=e=>{uploadFiles([...e.target.files]);e.target.value=''};let drag=0;window.addEventListener('dragenter',e=>{e.preventDefault();drag++;$('dropMask').hidden=false});window.addEventListener('dragover',e=>e.preventDefault());window.addEventListener('dragleave',e=>{e.preventDefault();drag--;if(drag<=0){drag=0;$('dropMask').hidden=true}});window.addEventListener('drop',e=>{e.preventDefault();drag=0;$('dropMask').hidden=true;uploadFiles([...e.dataTransfer.files])});$('providerBtn').onclick=()=>$('providerModal').hidden=false;$('settingsBtn').onclick=()=>$('providerModal').hidden=false;$('providerModal').onclick=e=>{if(e.target===$('providerModal')||e.target.closest('.modal-close'))$('providerModal').hidden=true};$('assetLibraryBtn').onclick=()=>setRightPanel('assets');$('shareBtn').onclick=async()=>{try{const u=new URL(location.href);if(state.conversation?.id)u.searchParams.set('conversation',state.conversation.id);await navigator.clipboard.writeText(u.toString());toast('任务链接已复制')}catch{toast('复制失败')}};$('moreBtn').onclick=()=>toast('更多操作可接入归档、导出和工单系统');document.addEventListener('click',e=>{const b=e.target.closest('[data-copy]');if(!b)return;const m=state.messages.find(x=>x.id===b.dataset.copy);if(m)navigator.clipboard?.writeText(m.content).then(()=>toast('已复制'))});window.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='n'){e.preventDefault();newConversation(state.scene)}})}
async function boot(){bind();setScene('product_governance');try{await Promise.all([loadProviders(),loadConversations()]);const linked=new URLSearchParams(location.search).get('conversation');if(linked){try{await openConversation(linked);return}catch{toast('链接中的任务不存在，已打开最近任务')}}if(state.conversations.length)await openConversation(state.conversations[0].id);else await newConversation('product_governance')}catch(err){console.error(err);toast('服务连接失败，请检查后端')}}
boot();
